## This 2 functions are written for the generation of an invertible matrix in the first code and 
## the caching of the inverse of the generated matrix in the second code.


## This function creates a special "matrix" that can cache its inverse.

makeCacheMatrix <- function(x = matrix()) {
		i<- NULL
		set <- function(y) {
			x <<- y
			i <<- NULL
		}
		get <- function () x
		setinverse <- function(inverse) i<<-inverse
		getinverse <- function() i
		list(set = set, 
		     get = get,
		     setinverse = setinverse,
		     getinverse = getinverse)
}							



## This function computes the inverse of the special "matrix" generated by the makeCacheMatrix function above. 
## If the inverse has already been calculated (and the matrix has not changed), then the cachesolve should retrieve the inverse from the cache.


cacheSolve <- function(x, ...) {
	i <- x$getinverse()
	if(!is.null(i)){
		message("getting cached data")
		return(i)
	}
	data <- x$get()
	i <- solve(data, ...)
	x$setinverse(i)
	i
}